package provider

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/tasksquad/daemon/logger"
)

// OpenCode is the provider for sst/opencode CLI.
//
// OpenCode uses TypeScript plugins (`.ts` files in `.opencode/plugins/`).
// Setup() writes a plugin that accumulates assistant message text parts via
// message.part.updated events, marks them complete via message.updated, then
// on session.idle combines all parts and POSTs to /hooks/stop with the full text.
type OpenCode struct{}

func (p *OpenCode) Name() string { return "opencode" }

// Setup writes .opencode/plugins/tasksquad.ts in workDir.
// The plugin exports event handlers for lifecycle events following the Go SDK
// patterns (session.*, message.*, tool.*).
// It POSTs to the daemon's local hook server so the agent knows when to stop
// or when a response (reply) is available.
func (p *OpenCode) Setup(workDir string, hooksPort int, agentID string, taskID string) error {
	pluginDir := filepath.Join(workDir, ".opencode", "plugins")
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return err
	}
	// Remove the old .mjs plugin if present (migrated back to .ts).
	os.Remove(filepath.Join(pluginDir, "tasksquad.mjs")) //nolint:errcheck
	plugin := fmt.Sprintf(`// Auto-generated by tsq daemon — do not edit

export const TaskSquadPlugin = async ({ client }) => {
  await client.app.log({ body: { service: "tasksquad", level: "info", message: "Plugin initialized" } })

  const post = async (path, body) => {
    try {
      await fetch("http://localhost:%d" + path, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      })
    } catch (e) {
      await client.app.log({ body: { service: "tasksquad", level: "error", message: "hook error: " + e.message } })
    }
  }

  const messageCache = new Map()
  let pendingToolCount = 0
  let sessionIdleSent = false

  return {
    "event": async (input) => {
      const { event } = input

      if (event.type === "message.part.updated" && event.properties?.part) {
        const part = event.properties.part
        if (part.type === "text" && part.messageID) {
          if (!messageCache.has(part.messageID)) {
            messageCache.set(part.messageID, { sessionID: part.sessionID, textParts: [], completed: false })
          }
          const cached = messageCache.get(part.messageID)
          const existing = cached.textParts.find(p => p.id === part.id)
          if (existing) {
            existing.text = part.text || ""
          } else {
            cached.textParts.push({ id: part.id, text: part.text || "" })
          }
        }
      }

      if (event.type === "message.updated" && event.properties?.info) {
        const info = event.properties.info
        if (info.role === "assistant" && info.time?.completed && messageCache.has(info.id)) {
          messageCache.get(info.id).completed = true
        }
      }

      if (event.type === "tool.execute.before") {
        pendingToolCount++
        await client.app.log({ body: { service: "tasksquad", level: "info", message: "tool.execute.before: " + pendingToolCount } })
      }

      if (event.type === "tool.execute.after") {
        pendingToolCount = Math.max(0, pendingToolCount - 1)
        await client.app.log({ body: { service: "tasksquad", level: "info", message: "tool.execute.after: pending=" + pendingToolCount } })
        // When tools complete and session goes idle, send stop hook
        if (pendingToolCount === 0 && !sessionIdleSent) {
          let lastCompleted = null
          for (const [, cached] of messageCache.entries()) {
            if (cached.completed) lastCompleted = cached
          }
          const message = lastCompleted ? lastCompleted.textParts.map(p => p.text).join("") : ""
          await post("/hooks/stop?agent=%s&task_id=%s&provider=opencode", { stop_reason: "idle", message })
          sessionIdleSent = true
        }
      }

      if (event.type === "session.idle") {
        await client.app.log({ body: { service: "tasksquad", level: "info", message: "session.idle pending=" + pendingToolCount } })
        if (pendingToolCount === 0 && !sessionIdleSent) {
          let lastCompleted = null
          for (const [, cached] of messageCache.entries()) {
            if (cached.completed) lastCompleted = cached
          }
          const message = lastCompleted ? lastCompleted.textParts.map(p => p.text).join("") : ""
          await post("/hooks/stop?agent=%s&task_id=%s&provider=opencode", { stop_reason: "idle", message })
          sessionIdleSent = true
        }
      }

      if (event.type === "session.error") {
        await client.app.log({ body: { service: "tasksquad", level: "error", message: "session.error" } })
        await post("/hooks/stop?agent=%s&task_id=%s&provider=opencode", { stop_reason: "error", message: event.properties?.error?.message || "Unknown error" })
      }

      // Reset on new user message to handle multiple turns
      if (event.type === "session.updated" && event.properties?.info?.role === "user") {
        sessionIdleSent = false
        messageCache.clear()
        pendingToolCount = 0
      }
    },
  }
}
`, hooksPort, agentID, taskID, agentID, taskID, agentID, taskID)
	return os.WriteFile(filepath.Join(pluginDir, "tasksquad.ts"), []byte(plugin), 0644)
}

func (p *OpenCode) UsesHooks() bool            { return true }
func (p *OpenCode) Stdin(prompt string) string { return prompt }
func (p *OpenCode) Env(_ int) []string         { return nil }
func (p *OpenCode) ExtraArgs() []string        { return []string{"--print-logs"} }

// SetupVoice writes .opencode/plugins/speechtotsq.ts in workDir.
// The plugin fires /hooks/speech-to-md/notification when the session goes idle,
// carrying the last accumulated assistant message text. Follows the same
// session.idle / tool.execute.after dedup pattern as the inbox tasksquad.ts plugin.
func (p *OpenCode) SetupVoice(workDir string, hooksPort int) error {
	pluginDir := filepath.Join(workDir, ".opencode", "plugins")
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return err
	}
	plugin := fmt.Sprintf(`// Auto-generated by tsq daemon — speech-to-md plugin

export const SpeechToTSDPlugin = async ({ client }) => {
  await client.app.log({ body: { service: "tasksquad-speech", level: "info", message: "Speech-to-md plugin initialized" } })

  const post = async (path, body) => {
    try {
      await fetch("http://localhost:%d" + path, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      })
    } catch (e) {
      await client.app.log({ body: { service: "tasksquad-speech", level: "error", message: "hook error: " + e.message } })
    }
  }

  const messageCache = new Map()
  let pendingToolCount = 0
  let sessionIdleSent = false

  return {
    "event": async (input) => {
      const { event } = input

      if (event.type === "message.part.updated" && event.properties?.part) {
        const part = event.properties.part
        if (part.type === "text" && part.messageID) {
          if (!messageCache.has(part.messageID)) {
            messageCache.set(part.messageID, { sessionID: part.sessionID, textParts: [], completed: false })
          }
          const cached = messageCache.get(part.messageID)
          const existing = cached.textParts.find(p => p.id === part.id)
          if (existing) {
            existing.text = part.text || ""
          } else {
            cached.textParts.push({ id: part.id, text: part.text || "" })
          }
        }
      }

      if (event.type === "message.updated" && event.properties?.info) {
        const info = event.properties.info
        if (info.role === "assistant" && info.time?.completed && messageCache.has(info.id)) {
          messageCache.get(info.id).completed = true
        }
      }

      if (event.type === "tool.execute.before") {
        pendingToolCount++
        await client.app.log({ body: { service: "tasksquad-speech", level: "info", message: "tool.execute.before: " + pendingToolCount } })
      }

      if (event.type === "tool.execute.after") {
        pendingToolCount = Math.max(0, pendingToolCount - 1)
        await client.app.log({ body: { service: "tasksquad-speech", level: "info", message: "tool.execute.after: pending=" + pendingToolCount } })
        if (pendingToolCount === 0 && !sessionIdleSent) {
          let lastCompleted = null
          for (const [, cached] of messageCache.entries()) {
            if (cached.completed) lastCompleted = cached
          }
          const message = lastCompleted ? lastCompleted.textParts.map(p => p.text).join("") : ""
          await post("/hooks/stop?speech=true&provider=opencode", { stop_reason: "idle", message })
          sessionIdleSent = true
        }
      }

      if (event.type === "session.idle") {
        await client.app.log({ body: { service: "tasksquad-speech", level: "info", message: "session.idle pending=" + pendingToolCount } })
        if (pendingToolCount === 0 && !sessionIdleSent) {
          let lastCompleted = null
          for (const [, cached] of messageCache.entries()) {
            if (cached.completed) lastCompleted = cached
          }
          const message = lastCompleted ? lastCompleted.textParts.map(p => p.text).join("") : ""
          await post("/hooks/stop?speech=true&provider=opencode", { stop_reason: "idle", message })
          sessionIdleSent = true
        }
      }

      if (event.type === "session.error") {
        await client.app.log({ body: { service: "tasksquad-speech", level: "error", message: "session.error" } })
      }

      // Reset on new user message to handle multiple chunks per session
      if (event.type === "session.updated" && event.properties?.info?.role === "user") {
        sessionIdleSent = false
        messageCache.clear()
        pendingToolCount = 0
      }
    },
  }
}
`, hooksPort)
	if err := os.WriteFile(filepath.Join(pluginDir, "speechtotsq.ts"), []byte(plugin), 0644); err != nil {
		return err
	}
	logger.Debug(fmt.Sprintf("[provider/opencode] Wrote voice plugin to %s (port %d)", pluginDir, hooksPort))
	return nil
}
