package provider

import (
	"fmt"
	"os"
	"path/filepath"
)

// OpenCode is the provider for sst/opencode CLI.
//
// OpenCode uses JavaScript plugins (`.mjs` files in `.opencode/plugins/`).
// Setup() writes a plugin that calls back to the daemon hook server when the
// session finishes or errors, mirroring the Claude Code Stop hook flow.
//
// The plugin tracks the last assistant response across `message.updated` events,
// writes it as a Gemini-compatible JSON transcript file in the system temp dir,
// then passes that file's path to the /hooks/stop endpoint so the daemon can
// extract the final text via ExtractTranscriptResponse.
type OpenCode struct{}

func (p *OpenCode) Name() string { return "opencode" }

// Setup writes .opencode/plugins/tasksquad.mjs in workDir.
// The plugin exports event handlers for lifecycle events following the Go SDK
// patterns (session.*, message.*).
// It POSTs to the daemon's local hook server so the agent knows when to stop
// or when a response (reply) is available.
func (p *OpenCode) Setup(workDir string, hooksPort int, agentName string) error {
	pluginDir := filepath.Join(workDir, ".opencode", "plugins")
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return err
	}
	plugin := fmt.Sprintf(`// Auto-generated by tsq daemon — do not edit
import { type Plugin } from "@opencode-ai/plugin";
import { writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"

export const TaskSquadPlugin: Plugin = async ({ client }) => {
  await client.app.log({ body: { service: "tasksquad", level: "info", message: "Plugin initializing" } })

  const post = async (path, body) => {
    await client.app.log({ body: { service: "tasksquad", level: "debug", message: "POST " + path, data: body } })
    try {
      await fetch("http://127.0.0.1:%d" + path, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      })
    } catch (e) {
      await client.app.log({ body: { service: "tasksquad", level: "error", message: "hook error: " + e.message } })
    }
  }

  // Path for the transcript file written after each assistant turn.
  const transcriptFile = join(tmpdir(), "tsq-oc-" + agentName + ".json")
  let lastTranscriptPath = ""
  let lastMessage = ""

  // Extract plain text from an opencode message object.
  const extractText = (message) => {
    if (typeof message.content === "string") return message.content
    if (Array.isArray(message.content)) {
      return message.content.filter(p => p.type === "text").map(p => p.text || "").join("")
    }
    return "Failed to extract response"
  }

  return {
    // This hook triggers for every message in the chat
    "chat.message": async ({}, { message }) => {
      await client.app.log({ body: { service: "tasksquad", level: "debug", message: "chat.message, role: " + message.role } })

      if (message.role === "assistant") {
        const text = extractText(message)
        lastMessage = text || ""
        await client.app.log({ body: { service: "tasksquad", level: "info", message: "assistant: " + (text?.slice(0, 50) || "empty") } })

        if (text) {
          try {
            writeFileSync(transcriptFile,
              JSON.stringify({ messages: [{ type: "assistant", content: text }] }))
            lastTranscriptPath = transcriptFile
            await client.app.log({ body: { service: "tasksquad", level: "info", message: "wrote transcript: " + transcriptFile } })
          } catch (e) {
            await client.app.log({ body: { service: "tasksquad", level: "error", message: "write error: " + e.message } })
          }
        }

        await post("/hooks/notification?agent=%s&provider=opencode", {
          message: lastMessage,
          transcript_path: lastTranscriptPath
        })
      }

      if (message.role === "user") {
        await client.app.log({ body: { service: "tasksquad", level: "debug", message: "user message received" } })
      }
    },

    "session.idle": async ({}) => {
      await client.app.log({ body: { service: "tasksquad", level: "info", message: "session.idle - sending stop" } })
      await post("/hooks/stop?agent=%s&provider=opencode", {
        stop_reason: "idle",
        transcript_path: lastTranscriptPath,
        message: lastMessage
      })
    },

    "session.error": async ({ error }) => {
      await client.app.log({ body: { service: "tasksquad", level: "info", message: "session.error: " + (error?.message || "unknown") } })
      await post("/hooks/stop?agent=%s&provider=opencode", {
        stop_reason: "error",
        message: error?.message || "Unknown error",
        transcript_path: lastTranscriptPath
      })
    },

    "session.created": async ({}) => {
      await client.app.log({ body: { service: "tasksquad", level: "info", message: "session.created" } })
    },
  }
}
`, hooksPort, agentName, agentName)
	return os.WriteFile(filepath.Join(pluginDir, "tasksquad.mjs"), []byte(plugin), 0644)
}

func (p *OpenCode) UsesHooks() bool            { return true }
func (p *OpenCode) Stdin(prompt string) string { return prompt }
func (p *OpenCode) Env(_ int) []string         { return nil }
func (p *OpenCode) ExtraArgs() []string        { return nil }
