package provider

import (
	"fmt"
	"os"
	"path/filepath"
)

// OpenCode is the provider for sst/opencode CLI.
//
// OpenCode uses JavaScript plugins (`.mjs` files in `.opencode/plugins/`).
// Setup() writes a plugin that calls back to the daemon hook server when the
// session finishes or errors, mirroring the Claude Code Stop hook flow.
type OpenCode struct{}

func (p *OpenCode) Name() string { return "opencode" }

// Setup writes .opencode/plugins/tasksquad.mjs in workDir.
// The plugin exports event handlers for "session.idle" and "session.error"
// that POST to the daemon's local hook server so the agent knows when to stop.
func (p *OpenCode) Setup(workDir string, hooksPort int, agentName string) error {
	pluginDir := filepath.Join(workDir, ".opencode", "plugins")
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return err
	}
	plugin := fmt.Sprintf(`// Auto-generated by tsq daemon — do not edit
export const TaskSquadPlugin = async ({ $ }) => {
  const post = async (path, body) => {
    try {
      await fetch("http://127.0.0.1:%d" + path, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body)
      })
    } catch (_) {}
  }
  return {
    "session.idle":  async () => post("/hooks/stop?agent=%s&provider=opencode", { stop_reason: "idle" }),
    "session.error": async () => post("/hooks/stop?agent=%s&provider=opencode", { stop_reason: "error" }),
  }
}
`, hooksPort, agentName, agentName)
	return os.WriteFile(filepath.Join(pluginDir, "tasksquad.mjs"), []byte(plugin), 0644)
}

func (p *OpenCode) UsesHooks() bool          { return true }
func (p *OpenCode) Stdin(prompt string) string { return prompt }
func (p *OpenCode) Env(_ int) []string        { return nil }
func (p *OpenCode) ExtraArgs() []string       { return nil }
