package provider

import (
	"fmt"
	"os"
	"path/filepath"
)

// Pi is the provider for the pi.dev coding agent CLI.
//
// Pi uses TypeScript extensions (`.ts` files in `.pi/extensions/`).
// Setup() writes an extension using pi's native ExtensionAPI (default export function)
// that captures the final assistant message via message_end and fires the stop
// hook on agent_end, POSTing to /hooks/stop with the full text.
type Pi struct{}

func (p *Pi) Name() string    { return "pi" }
func (p *Pi) CLIName() string { return "pi" }

// Setup writes .pi/extensions/tasksquad.ts in workDir.
// The extension uses pi's ExtensionAPI event system: message_end to capture
// assistant text, agent_end to POST /hooks/stop, before_agent_start to reset
// state between turns.
func (p *Pi) Setup(workDir string, hooksPort int, agentID string, taskID string) error {
	extDir := filepath.Join(workDir, ".pi", "extensions")
	if err := os.MkdirAll(extDir, 0755); err != nil {
		return err
	}
	ext := fmt.Sprintf(`// Auto-generated by tsq daemon — do not edit

export default function(pi) {
  const post = async (path, body, signal) => {
    try {
      await fetch("http://localhost:%d" + path, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body), signal,
      })
    } catch (e) {
      console.error("[tasksquad] hook error:", e?.message)
    }
  }

  const extractText = (content) =>
    (content || []).filter(c => c.type === "text").map(c => c.text || "").join("")

  // Provider errors arrive as JSON nested inside JSON strings; unwrap to the
  // innermost human-readable message.
  const describeError = (raw) => {
    let s = String(raw || "")
    for (let i = 0; i < 4; i++) {
      try {
        const m = JSON.parse(s)?.error?.message ?? JSON.parse(s)?.message
        if (typeof m !== "string") break
        s = m
      } catch { break }
    }
    return s.trim()
  }

  let lastAssistantMessage = ""
  let lastError = ""

  pi.on("before_agent_start", async (_event, _ctx) => {
    lastAssistantMessage = ""
    lastError = ""
  })

  pi.on("message_end", async (event, _ctx) => {
    if (event.message?.role === "assistant") {
      const text = extractText(event.message.content)
      if (text) lastAssistantMessage = text
      if (event.message.stopReason === "error") {
        const where = [event.message.provider, event.message.model].filter(Boolean).join("/")
        lastError = "Pi model call failed" + (where ? " (" + where + ")" : "") + ": " +
          (describeError(event.message.errorMessage) || "unknown error")
      }
    }
  })

  pi.on("agent_end", async (event, ctx) => {
    const msgs = event.messages || []
    for (let i = msgs.length - 1; i >= 0; i--) {
      if (msgs[i].role === "assistant") {
        const text = extractText(msgs[i].content)
        if (text) { lastAssistantMessage = text; break }
      }
    }
    const transcriptPath = ctx.sessionManager?.getSessionFile?.() ?? ""
    const failed = !lastAssistantMessage && lastError
    await post(
      "/hooks/stop?agent=%s&task_id=%s&provider=pi",
      {
        stop_reason: failed ? "error" : "idle",
        message: failed ? lastError : lastAssistantMessage,
        transcript_path: transcriptPath,
      },
      ctx.signal
    )
  })
}
`, hooksPort, agentID, taskID)
	return os.WriteFile(filepath.Join(extDir, "tasksquad.ts"), []byte(ext), 0644)
}

func (p *Pi) UsesHooks() bool                       { return true }
func (p *Pi) Stdin(_ string) string                 { return "" }
func (p *Pi) Env(_ int) []string                    { return nil }
func (p *Pi) ExtraArgs() []string                   { return nil }
func (p *Pi) SetupArgs(_ int, _, _ string) []string { return nil }
