package provider

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/tasksquad/daemon/logger"
)

// Pi is the provider for the pi.dev coding agent CLI.
//
// Pi uses TypeScript extensions (`.ts` files in `.pi/extensions/`).
// Setup() writes an extension using pi's native ExtensionAPI (default export function)
// that captures the final assistant message via message_end and fires the stop
// hook on agent_end, POSTing to /hooks/stop with the full text.
type Pi struct{}

func (p *Pi) Name() string    { return "pi" }
func (p *Pi) CLIName() string { return "pi" }

// Setup writes .pi/extensions/tasksquad.ts in workDir.
// The extension uses pi's ExtensionAPI event system: message_end to capture
// assistant text, agent_end to POST /hooks/stop, before_agent_start to reset
// state between turns.
func (p *Pi) Setup(workDir string, hooksPort int, agentID string, taskID string) error {
	extDir := filepath.Join(workDir, ".pi", "extensions")
	if err := os.MkdirAll(extDir, 0755); err != nil {
		return err
	}
	ext := fmt.Sprintf(`// Auto-generated by tsq daemon — do not edit

export default function(pi) {
  const post = async (path, body, signal) => {
    try {
      await fetch("http://localhost:%d" + path, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body), signal,
      })
    } catch (e) {
      console.error("[tasksquad] hook error:", e?.message)
    }
  }

  const extractText = (content) =>
    (content || []).filter(c => c.type === "text").map(c => c.text || "").join("")

  let lastAssistantMessage = ""

  pi.on("before_agent_start", async (_event, _ctx) => {
    lastAssistantMessage = ""
  })

  pi.on("message_end", async (event, _ctx) => {
    if (event.message?.role === "assistant") {
      const text = extractText(event.message.content)
      if (text) lastAssistantMessage = text
    }
  })

  pi.on("agent_end", async (event, ctx) => {
    const msgs = event.messages || []
    for (let i = msgs.length - 1; i >= 0; i--) {
      if (msgs[i].role === "assistant") {
        const text = extractText(msgs[i].content)
        if (text) { lastAssistantMessage = text; break }
      }
    }
    const transcriptPath = ctx.sessionManager?.getSessionFile?.() ?? ""
    await post(
      "/hooks/stop?agent=%s&task_id=%s&provider=pi",
      { stop_reason: "idle", message: lastAssistantMessage, transcript_path: transcriptPath },
      ctx.signal
    )
  })
}
`, hooksPort, agentID, taskID)
	return os.WriteFile(filepath.Join(extDir, "tasksquad.ts"), []byte(ext), 0644)
}

func (p *Pi) UsesHooks() bool            { return true }
func (p *Pi) Stdin(_ string) string      { return "" }
func (p *Pi) Env(_ int) []string         { return nil }
func (p *Pi) ExtraArgs() []string        { return nil }
func (p *Pi) SetupArgs(_ int, _, _ string) []string { return nil }
func (p *Pi) VoiceCLIArg() string        { return "" }
func (p *Pi) VoiceInitCommand() string   { return "/tsq-speech-to-md" }

// SetupVoice writes .pi/extensions/speechtotsq.ts in workDir.
// Fires /hooks/stop?speech=true&provider=pi when the agent turn completes,
// carrying the last accumulated assistant message for the speech-to-md handler.
func (p *Pi) SetupVoice(workDir string, hooksPort int) error {
	extDir := filepath.Join(workDir, ".pi", "extensions")
	if err := os.MkdirAll(extDir, 0755); err != nil {
		return err
	}
	ext := fmt.Sprintf(`// Auto-generated by tsq daemon — speech-to-md extension

export default function(pi) {
  const post = async (path, body, signal) => {
    try {
      await fetch("http://localhost:%d" + path, {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body), signal,
      })
    } catch (e) {
      console.error("[tasksquad-speech] hook error:", e?.message)
    }
  }

  const extractText = (content) =>
    (content || []).filter(c => c.type === "text").map(c => c.text || "").join("")

  let lastAssistantMessage = ""

  pi.on("before_agent_start", async (_event, _ctx) => {
    lastAssistantMessage = ""
  })

  pi.on("message_end", async (event, _ctx) => {
    if (event.message?.role === "assistant") {
      const text = extractText(event.message.content)
      if (text) lastAssistantMessage = text
    }
  })

  pi.on("agent_end", async (event, ctx) => {
    const msgs = event.messages || []
    for (let i = msgs.length - 1; i >= 0; i--) {
      if (msgs[i].role === "assistant") {
        const text = extractText(msgs[i].content)
        if (text) { lastAssistantMessage = text; break }
      }
    }
    await post(
      "/hooks/stop?speech=true&provider=pi",
      { stop_reason: "idle", message: lastAssistantMessage },
      ctx.signal
    )
  })
}
`, hooksPort)
	if err := os.WriteFile(filepath.Join(extDir, "speechtotsq.ts"), []byte(ext), 0644); err != nil {
		return err
	}
	logger.Debug(fmt.Sprintf("[provider/pi] Wrote voice extension to %s (port %d)", extDir, hooksPort))
	return nil
}
